base_url = "https://demilurii.art"
title = "Emilia Frias"
description = "Emilia is a skilled 2D Animator and Builds Artist, creating fun and lively cartoons"
default_language = "en"
compile_sass = true
build_search_index = true
generate_feeds = true
feed_filenames = ["rss.xml"]
minify_html = true

[markdown]
highlight_code = true
render_emoji = true
external_links_target_blank = true

[link_checker]
skip_prefixes = []
skip_anchor_prefixes = []
internal_level = "error"
external_level = "error"

[extra]
domain = "demilurii.art"